### ISSUE TITLE
Bugs in relativedelta

### ISSUE THREAD

**Issue by shaib** [paxan/python-dateutil#1]
Hi,

I'm using relativedelta, and have run into a couple of problems; thought to report them, and this seems like the only place where such reports may be welcome...

1) the `__mul__` operation transforms its argument to float, which breaks things; as a result:

``` python
>>> from datetime import date
>>> from dateutil.relativedelta import relativedelta as delta
>>> date.today() + delta(days=+1)*2
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File ".../site-packages/dateutil/relativedelta.py", line 261, in __radd__
    day = min(calendar.monthrange(year, month)[1],
  File "/usr/lib/python2.7/calendar.py", line 121, in monthrange
    day1 = weekday(year, month, 1)
  File "/usr/lib/python2.7/calendar.py", line 113, in weekday
    return datetime.date(year, month, day).weekday()
TypeError: integer argument expected, got float
```

2) I needed to subclass relativedelta (to fix the above, but also for other needs). Then, it was disappointing to find that the `__add__`, `__sub__` and `__neg__` operations explicitly return a new `relativedelta` object; it would be much nicer if they could return a `self.__class__` object.

Thanks for your continued effort,

Shai.

**Comment by shaib** [comment]
Oh, while we're at it: `__sub__` is reversed (that is, for `x` and `y` instances of relativedelta, the expression `x-y` calculates `y-x`.

**Comment by paxan** [comment]
You may want to report this to the maintainers of python-dateutil. This repo merely contains snapshots of official releases. Plus few little tweaks.

But I'll take a look at this.

**Comment by shaib** [comment]
On Thursday 07 June 2012, you wrote:

> You may want to report this to the maintainers of python-dateutil. This
> repo merely contains snapshots of official releases. Plus few little
> tweaks.

Sure. I somehow missed the reference to launchpad the first time I looked, and 
so I thought there was no other maintainer willing to check things. I'll take 
my complaints there.

> But I'll take a look at this.

Thanks,

Shai.
