### ISSUE TITLE
Permission denied after installing dateutil as a requirement to gsync

### ISSUE THREAD

**Issue by iwonbigbro** [paxan/python-dateutil#2]
See associated gsync issue: https://github.com/iwonbigbro/gsync/issues/24

**Comment by iwonbigbro** [comment]
Recommended installation procedure for gsync is to use pip.  If pip is not available, then it recommended that pip is installed using easy_install.  If easy_install is not available it is recommended that easy_install is installed by installing the distro package for python-setuptools.

**Comment by paxan** [comment]
I don't see how this issue is related to this repo.

**Comment by iwonbigbro** [comment]
Because it's a file distributed by the dateutil package that has the incorrect permissions when installed.

 '/usr/lib/python2.7/site-packages/python_dateutil-2.1-py2.7.egg/EGG-INFO/requires.txt'

**Comment by paxan** [comment]
Requires.txt?

**Comment by iwonbigbro** [comment]
It's created by setuptools when you run the setup.py to upload to pypi.org:

```
./setup.py sdist upload
```

Not sure how this file has ended up with the wrong permissions on pypi,org, but I would assume something modified them when dateutil got built.  

Personally, I don't care since it's not my package.  This bug was raised by someone that installed my gsync package.  My package uses dateutil, but dateutil raises permissions exceptions unless they modify the permissions on this file.  If they uninstall and reinstall dateutil, the requires.txt distributed with dateutil has the wrong permissions and raises exceptions.

It has something to do with the way setuptools bundles things in wrapper functions to ensure the correct or latest version of the module is loaded.  I presume you just need to resubmit the build to pypi and the problem will go away.  Who knows?

**Comment by paxan** [comment]
FYI, this repo is a snapshot of python-dateutil that has some fixes applied to it. I've made it because the official package was not on GitHub. This version had never been on Pypi. What you have on Pypi is the official version that I don't maintain.
